### PR TITLE
Count number of orders of a token

### LINKED ISSUE #500: Report "Number of orders" for each datatoken
Can we have the number of orders for each datatoken? Each asset has multiple services, each service has a datatoken and it would be nice to know how many times each service was ordered and a total orders per asset.

This is useful to create sections like best sellers and give the publisher some quick stats.
For detailed orders and graphs we can fetch the orders from the subgraph.

Watch for startOrder events on the blockchain and when the event is registered, fetch the graph for that asset.
Use a graphQL lib for fetching the graph(doesn't require authentication)

### PR DESCRIPTION
**Pull request by calina-c**
Closes #500

Pending tasks:
- subgraph query
- testing

### CODE REVIEW

**Comment by alexcos20** [comment]
looks good so far

**Comment by kremalicious** [comment]
We should first decide if we suddenly want to break what we established, that Aquarius caches what's in our metadata contract, and that's it, see https://github.com/oceanprotocol/aquarius/issues/500#issuecomment-935690718

**Comment by calina-c** [comment]
Repurposed the same issue for v4. Currently in work, but I need some help detecting the event, something is off. Marking this as blocked for now.

**Comment by calina-c** [comment]
Event is fine, now blocked by contracts. We need a function in contracts to retrieve the corresponding NFT address that "parents" an ERC20 token. Alex is currently doing that in contracts, and I will update this task accordingly, when possible.

**Comment by calina-c** [comment]
Superceded in v4.

**Pull request closed without merging**
