### PR TITLE
Expose schema

### LINKED ISSUE #871: Expose the shacl validation schema
Investigate a way to properly expose the shacl fields restrictions/limitations

### PR DESCRIPTION
**Pull request by calina-c**
Closes #871.

### CODE REVIEW

**Comment by calina-c** [comment]
Here is a sample:

```{
  "chainId": {
    "maxCount": 1,
    "minCount": 1
  },
  "credentials": {
    "allow": {
      "type": {
        "maxCount": 1,
        "maxLength": 256,
        "minCount": 1,
        "pattern": "^(.*)$"
      },
      "values": {
        "maxLength": 1024,
        "minCount": 1,
        "pattern": "^(.*)$"
      }
    },
    "deny": {
      "type": {
        "maxCount": 1,
        "maxLength": 256,
        "minCount": 1,
        "pattern": "^(.*)$"
      },
      "values": {
        "maxLength": 1024,
        "minCount": 1,
        "pattern": "^(.*)$"
      }
    }
  },
  "id": {
    "maxCount": 1,
    "maxLength": 71,
    "minCount": 1,
    "minLength": 71,
    "pattern": "^did\\:op\\:(.*)$"
  },
  "metadata": {
    "additionalInformation": {},
    "algorithm": {
      "consumerParameters": {
        "default": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        },
        "description": {
          "maxCount": 1,
          "maxLength": 7000,
          "minCount": 1,
          "pattern": "^((.|\n)*)$"
        },
        "label": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        },
        "name": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        },
        "options": {
          "maxLength": 256,
          "pattern": "^(.*)$"
        },
        "required": {
          "maxCount": 1,
          "minCount": 1
        },
        "type": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        }
      },
      "container": {
        "checksum": {
          "maxCount": 1,
          "maxLength": 512,
          "minCount": 1,
          "minLength": 7,
          "pattern": "^(.*)$"
        },
        "entrypoint": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        },
        "image": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        },
        "tag": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        }
      },
      "language": {
        "maxCount": 1,
        "maxLength": 256,
        "pattern": "^(.*)$"
      },
      "version": {
        "maxCount": 1,
        "maxLength": 256,
        "pattern": "^(.*)$"
      }
    },
    "author": {
      "maxCount": 1,
      "maxLength": 256,
      "minCount": 1,
      "pattern": "^(.|\\s)*$"
    },
    "categories": {
      "maxCount": 64,
      "maxLength": 256,
      "pattern": "^(.|\\s)*$"
    },
    "contentLanguage": {
      "maxCount": 1,
      "maxLength": 256,
      "pattern": "^(.|\\s)*$"
    },
    "copyrightHolder": {
      "maxCount": 1,
      "maxLength": 512,
      "pattern": "^(.|\\s)*$"
    },
    "description": {
      "maxCount": 1,
      "maxLength": 7000,
      "minCount": 1,
      "pattern": "^((.|\n)*)$"
    },
    "license": {
      "maxCount": 1,
      "maxLength": 256,
      "minCount": 1,
      "pattern": "^(.|\\s)*$"
    },
    "links": {
      "maxCount": 64,
      "maxLength": 512,
      "pattern": "^(.|\\s)*$"
    },
    "name": {
      "maxCount": 1,
      "maxLength": 512,
      "minCount": 1,
      "pattern": "^(.|\\s)*$"
    },
    "tags": {
      "maxCount": 64,
      "maxLength": 256,
      "pattern": "^(.|\\s)*$"
    },
    "type": {
      "maxCount": 1,
      "maxLength": 256,
      "minCount": 1,
      "pattern": "^(.|\\s)*$"
    }
  },
  "nftAddress": {
    "maxCount": 1,
    "maxLength": 42,
    "minCount": 1,
    "minLength": 42
  },
  "services": {
    "additionalInformation": {},
    "compute": {
      "allowNetworkAccess": {
        "maxCount": 1,
        "minCount": 1
      },
      "allowRawAlgorithm": {
        "maxCount": 1,
        "minCount": 1
      },
      "publisherTrustedAlgorithmPublishers": {
        "maxLength": 256,
        "pattern": "^(.*)$"
      },
      "publisherTrustedAlgorithms": {
        "containerSectionChecksum": {
          "maxCount": 1,
          "maxLength": 1024,
          "minCount": 1,
          "pattern": "^(.*)$"
        },
        "did": {
          "maxCount": 1,
          "maxLength": 256,
          "minCount": 1,
          "pattern": "^(.*)$"
        },
        "filesChecksum": {
          "maxCount": 1,
          "maxLength": 1024,
          "minCount": 1,
          "pattern": "^(.*)$"
        }
      }
    },
    "consumerParameters": {
      "default": {
        "maxCount": 1,
        "maxLength": 256,
        "minCount": 1,
        "pattern": "^(.*)$"
      },
      "description": {
        "maxCount": 1,
        "maxLength": 7000,
        "minCount": 1,
        "pattern": "^((.|\n)*)$"
      },
      "label": {
        "maxCount": 1,
        "maxLength": 256,
        "minCount": 1,
        "pattern": "^(.*)$"
      },
      "name": {
        "maxCount": 1,
        "maxLength": 256,
        "minCount": 1,
        "pattern": "^(.*)$"
      },
      "options": {
        "maxLength": 256,
        "pattern": "^(.*)$"
      },
      "required": {
        "maxCount": 1,
        "minCount": 1
      },
      "type": {
        "maxCount": 1,
        "maxLength": 256,
        "minCount": 1,
        "pattern": "^(.*)$"
      }
    },
    "datatokenAddress": {
      "maxCount": 1,
      "maxLength": 42,
      "minCount": 1,
      "minLength": 42,
      "pattern": "^(.*)$"
    },
    "description": {
      "maxCount": 1,
      "maxLength": 7000,
      "minLength": 10,
      "pattern": "^((.|\\n)*)$"
    },
    "files": {
      "maxCount": 1,
      "maxLength": 8192,
      "minCount": 1,
      "pattern": "^(.*)$"
    },
    "id": {
      "maxCount": 1,
      "maxLength": 256,
      "minCount": 1,
      "pattern": "^(.*)$"
    },
    "name": {
      "maxCount": 1,
      "maxLength": 256,
      "minLength": 4,
      "pattern": "^(.*)$"
    },
    "serviceEndpoint": {
      "maxCount": 1,
      "maxLength": 2048,
      "minCount": 1,
      "minLength": 10,
      "pattern": "^(.*)$"
    },
    "timeout": {
      "maxCount": 1,
      "minCount": 1,
      "pattern": "^(.*)$"
    },
    "type": {
      "maxCount": 1,
      "maxLength": 256,
      "minCount": 1,
      "pattern": "^(.*)$"
    }
  },
  "version": {
    "maxCount": 1,
    "maxLength": 16,
    "minCount": 1,
    "pattern": "^(.*)$"
  }
}

**Comment by EnzoVezzaro** [comment]
Hi @calina-c , found some values on the frontend that don't show up on the schema.

on the Metadata object is missing: 
- name: missing `minLength` (I have `4` in the frontend)
- description: missing `minLength` (I have `10` in the frontend)
- termsAndConditions: I don't see this field in the schema, is perhaps this field `license`? or we're not tracking this, and it's only a frontend thing?

This is what I have so far, but probably I'll be posting more along the way.

**Comment by calina-c** [comment]
@EnzoVezzaro I think termsAndConditions is only a frontend thing, possibly where you submit the form and it needs to check some publishing T&C. I'll look into the other two :)

**Comment by EnzoVezzaro** [comment]
Hi @calina-c 👋🏽 I found some other parameters that's being handle differently on the market.

On the market I have the following objects:

- `dataTokenOptions` with `name: string` and `symbol: string` properties (on the schema I see: `datatokenAddress`, it might be that we handle these properties just on the market).
- I also have a property call `providerUrl`, is this the same as `serviceEndpoint`

I also notice that on the schema under the object `services`, we have the `name` and `description` with `minLength` set correctly, not sure why it's under `services` though. We might just want to added the same to the `metadata` properties.

**Comment by calina-c** [comment]
@EnzoVezzaro here's what I have:
```
response_json["metadata"]["name"]
{'maxCount': 1, 'maxLength': 512, 'minCount': 1, 'pattern': '^(.|\\s)*$'}

response_json["services"]["name"]
{'maxCount': 1, 'maxLength': 256, 'minLength': 4, 'pattern': '^(.*)$'}
```

this seems in alignment with the schema itself. Are these the values that you get, as well, or ar they missing somehow? Do you think they should hold the same values?

**Comment by EnzoVezzaro** [comment]
> @EnzoVezzaro here's what I have:
> 
> ```
> response_json["metadata"]["name"]
> {'maxCount': 1, 'maxLength': 512, 'minCount': 1, 'pattern': '^(.|\\s)*$'}
> 
> response_json["services"]["name"]
> {'maxCount': 1, 'maxLength': 256, 'minLength': 4, 'pattern': '^(.*)$'}
> ```
> 
> this seems in alignment with the schema itself. Are these the values that you get, as well, or ar they missing somehow? Do you think they should hold the same values?

Hi @calina-c 👋🏽 basically on the frontend I have `minLength` set both `name` (4 char) and `description` (10 char) on the `metadata` object, so I think we only need these on the frontend:

response_json["metadata"]["name"]
{'maxCount': 1, 'maxLength': 256, 'minLength': 4, 'pattern': '^(.*)$'}

response_json["metadata"]["description"]
{'maxCount': 1, 'maxLength': 7000, 'minLength': 10, 'pattern': '^(.*)$'}

 I don't have neither `name` or `description` on the `services` object.

**Comment by calina-c** [comment]
As discussed, I'm merging this and we are doing the changes in the schema upgrade, since the issue is with the schema itself and not the exposition endpoint.

**Pull request merged**
