### PR TITLE
Deployment docs

### PR DESCRIPTION
**Pull request by md00ux**
## Description

Add a description of your changes here.

## Is this PR related with an open issue?

Related to Issue #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [x] Documentation

#### Funny gif

Put a link of a funny gif inside the parenthesis-->

### CODE REVIEW

**Comment by alexcos20** [comment]
closes #355

**Comment by kremalicious** [comment]
cool! Although it's not really docs so I would either do one of those things:

1. create README.md in that newly created `docs/` folder, and describe and link to the deployment files from there, or
2. rename folder to `deployment/`. If those files are examples and not our production deployment files, then their filenames should reflect that, like adding `-example` at end of file names

In both cases, the main Readme should then have a section listing and referencing those deployment files, quickly saying what they are (our production files? example?)

**Comment by md00ux** [comment]
Renamed the directory to deployment/ and files names contains *example* .
Once I will add to the deployment/ other files (eg. docker-compose ) I will create Readme and maybe we will reference as separate section the the main README.

**Comment by kremalicious** [comment]
Is there another PR being prepared or was this closed by accident?

**Comment by md00ux** [comment]
This PR was automatically closed due to branch renaming.
Will issue another one.

**Pull request closed without merging**
