### PR TITLE
Add docstrings

### PR DESCRIPTION
**Pull request by akshay-ap**
## Description

Add doc string for methods and modules to improve the documentation content.

## Is this PR related with an open issue?

Related to Issue #517 

## Types of changes

- [x] Add doc strings for methods and modules

## Checklist:

- [x] Follows the code style of this project.
- [x] Tests Cover Changes
- [x] Documentation

### CODE REVIEW

**Comment by calina-c** [comment]
@akshay-ap Please work in the stable-aqua branch and create the PR with a `stable-aqua` base.

**Comment by calina-c** [comment]
Please rebase this, since stable-aqua is now merged. I would suggest closing this PR, creating a new branch and cherry picking the relevant commits.

**Comment by calina-c** [comment]
Superseded by #528, which is the rebased version.

**Comment by akshay-ap** [comment]
@calina-c Thank you rebase!

**Pull request closed without merging**
