### PR TITLE
Adapt datatoken language.

### LINKED ISSUE #668: Replace "dataToken" -> "datatoken" etc, everywhere
**Is your feature request related to a problem? Please describe.**

It's not "data token". There is no space,  it's "datatoken"; It's a single word; there are several reasons for this. 

v3 wasn't filly consistent this way. Let's take the opportunity to make v4 consistent, before we ship the first version.

**Describe the solution you'd like**
https://github.com/oceanprotocol/aquarius/search?q=datatoken
Everywhere in aquarius, replace:
- "data token" -> "datatoken"
- "data_token" -> "datatoken"
- "dataToken" -> "datatoken"
- "DataToken" -> "Datatoken"
- "Data Token" -> "Datatoken"
- etc

**Additional context**
A "datatoken" is the ERC20 fungible token. Complementary to it is the "Data NFT", an ERC721 non-fungible token. "Data NFT" _does_ have a space.

Related issues: [ocean contracts](https://github.com/oceanprotocol/contracts/issues/450), [ocean.js](https://github.com/oceanprotocol/ocean.js/issues/1217)

### PR DESCRIPTION
**Pull request by calina-c**
Done, but waiting for other repos to sync the change.
Closes #668

### CODE REVIEW

**Comment by alexcos20** [comment]
@mihaisc @kremalicious - pls let us know once we can merge this

**Review by alexcos20 — APPROVED** [review]

**Comment by mihaisc** [comment]
This is related to v3 right?

**Comment by kremalicious** [comment]
why are we changing this in v3? This change requires us to update the v3 market

**Comment by calina-c** [comment]
it's v4.

**Pull request merged**
