### PR TITLE
Adds test for exchange created.

### PR DESCRIPTION
**Pull request by calina-c**
## Description

Adds test for exchange created. The tests will fail due to a problem with BPool.

### CODE REVIEW

**Comment by DMats** [comment]
@calina-c
CC @alexcos20 
As you know, `tests/test_events.py::test_fixed_rate_events` fails with the following error:

```console
______________________________________________________________________________________ test_fixed_rate_events ______________________________________________________________________________________

client = <FlaskClient <Flask 'aquarius.myapp'>>, base_ddo_url = '/api/v1/aquarius/assets/ddo', events_object = <aquarius.events.events_monitor.EventsMonitor object at 0x7f3c2d847df0>

    def test_fixed_rate_events(client, base_ddo_url, events_object):
        _ddo, published_ddo = do_publish(client, base_ddo_url, events_object)
        dt_address_2 = deploy_datatoken(
            get_web3(), test_account1.privateKey, "dt.1", "dt.1", test_account1.address
        )
        ox = OceanExchange(
            dt_address_2, _get_exchange_address(), ConfigProvider.get_config()
        )
        test_account1_wallet = Wallet(get_web3(), private_key=test_account1.privateKey)
        x_id = ox.create(_ddo["dataToken"], 0.9, test_account1_wallet)
        events_object._process_pool_events()
        published_ddo = get_ddo(client, base_ddo_url, _ddo.id)
>       assert published_ddo["price"]["exchange_id"] == "0x" + x_id.hex()
E       AssertionError: assert '' == '0xfff9b89e97...c208ed6997043'
E         - 0xfff9b89e9717b31bd3d9a5f07d04dec5e8ceabbea9690c2865fc208ed6997043
```

The issue is that `process_pool_events()` returns without processing because the current block number is lower than the last processed block. At the moment it returns, `block` == 122 and `last_block`== 11644795

metadata_updater.py::729-738
```python
    def process_pool_events(self):
        try:
            last_block = self.get_last_processed_block()
        except Exception as e:
            logger.warning(f"exception thrown reading last_block from db: {e}")
            last_block = 0

        block = self._web3.eth.blockNumber
        if not block or not isinstance(block, int) or block <= last_block:
            return //<-- this is where it returns
<snip>
```

**Comment by DMats** [comment]
From @calina-c via Slack
>I am certain you are not using the right network there, out of config complications. Because tests set up the block to be 0
>so we’ll look into that tomorrow

**Comment by DMats** [comment]
@calina-c and I spent an hour and a half attempting to debug the error I am seeing (where the block number is lower than the processed block). Calina explained that the error she sees is actually different from mine (her's fails at a later instruction) and that neither of our errors occurs in Github actions.

Our suspicion is that both of our errors are caused by configuration problems. Unfortunately, we were unable to fix either of our errors during our debugging session.

**Comment by calina-c** [comment]
This is now temporarily abandoned. Aquarius seems to behave strangely and we can't make any advances testing without a more clear strategy.

**Pull request closed without merging**
